if Exists(select CONSTRAINT_NAME from INFORMATION_SCHEMA.TABLE_CONSTRAINTS  where CONSTRAINT_NAME='PK_SGS_SECURITY_ROLE_ID_RESOURCE_ID_SECURITY_ID_SECURITY_VALUE')
begin
ALTER TABLE SGS_SECURITY DROP CONSTRAINT PK_SGS_SECURITY_ROLE_ID_RESOURCE_ID_SECURITY_ID_SECURITY_VALUE;
end
else
begin
print 'PK_SGS_SECURITY_ROLE_ID_RESOURCE_ID_SECURITY_ID_SECURITY_VALUE constraint not present already removed from table SGS_SECURITY';
end

if not Exists(select COLUMN_NAME from INFORMATION_SCHEMA.COLUMNS where COLUMN_NAME='SECURITY_SERIAL_ID')
begin
 ALTER TABLE SGS_SECURITY ADD SECURITY_SERIAL_ID INT IDENTITY(1, 1) NOT NULL;
end
else
begin
	print 'SECURITY_SERIAL_ID INT already exists int table SGS_SECURITY';
end


if not Exists(select CONSTRAINT_NAME from INFORMATION_SCHEMA.TABLE_CONSTRAINTS  where CONSTRAINT_NAME='PK_SGS_SECURITY_SECURITY_SERIAL_ID')
begin
	ALTER TABLE SGS_SECURITY ADD CONSTRAINT PK_SGS_SECURITY_SECURITY_SERIAL_ID PRIMARY KEY(SECURITY_SERIAL_ID);
end
else
begin
	print'PK_SGS_SECURITY_SECURITY_SERIAL_ID constraint already exists in table SGS_SECURITY';
end